INSERT INTO CATEGORIA (ID_CATEGORIA, NOM_CAT)
SELECT ID_CATEGORIA, NOM_CAT
FROM [BASE_UPS].UPS.[public].categoria


/*MATERIA Y CARRERA*/
INSERT INTO CARRERA_GIRON (ID_CARRERA, NOMBRE, N_SEMESTRES, CAMPUS, NODO)
SELECT ID_CARRERA, NOMBRE, N_SEMESTRES, CAMPUS, 1
FROM [BASE_UPS].UPS.[public].carrera
WHERE CAMPUS = 1

--temp
INSERT INTO MATERIA_CARRERA_GIRON (ID_MATERIA, ID_CARRERA, NODO)
SELECT ID_MATERIA, ID_CARRERA, 1
FROM [BASE_UPS].UPS.[public].materia_carrera
WHERE ID_CARRERA IN (SELECT ID_CARRERA from CARRERA_GIRON)

INSERT INTO MATERIA_GIRON (ID_MATERIA, NOMBRE, SEM_REF, N_CREDITOS, NODO)
SELECT ID_MATERIA, NOMBRE, SEM_REF, N_CREDITOS, 1
FROM [BASE_UPS].UPS.[public].materia
WHERE ID_MATERIA IN (SELECT ID_MATERIA from MATERIA_CARRERA_GIRON)

--vale
INSERT INTO MATERIA_GIRON (ID_MATERIA, NOMBRE, SEM_REF, N_CREDITOS, NODO)
SELECT ID_MATERIA, NOMBRE, SEM_REF, N_CREDITOS, 1
FROM temp_GIRON.dbo.MATERIA_GIRON

INSERT INTO MATERIA_CARRERA_GIRON (ID_MATERIA, ID_CARRERA, NODO)
SELECT ID_MATERIA, ID_CARRERA, 1
FROM [BASE_UPS].UPS.[public].materia_carrera
WHERE ID_CARRERA IN (SELECT ID_CARRERA from CARRERA_GIRON)



/*MATERIA Y PROFESOR*/
--temp
INSERT INTO PROFESOR_MATERIA_GIRON(ID_PROF, ID_MATERIA, NODO)
SELECT ID_PROF, ID_MATERIA, 1
FROM [BASE_UPS].UPS.[public].profesor_materia
WHERE ID_MATERIA IN (SELECT ID_MATERIA from MATERIA_GIRON)

INSERT INTO PROFESOR_DATOS_GIRON (ID_PROF, ID_CATEGORIA, NOMBRE_PROF, APELLIDO_PROF, EMAIL_PROF, CI_PROF, NODO)
SELECT ID_PROF, ID_CATEGORIA, NOMBRE_PROF, APELLIDO_PROF, EMAIL_PROF, CI_PROF, 1
FROM [BASE_UPS].UPS.[public].profesor
WHERE ID_PROF IN (SELECT ID_PROF from PROFESOR_MATERIA_GIRON)

--vale
INSERT INTO PROFESOR_DATOS_GIRON (ID_PROF, ID_CATEGORIA, NOMBRE_PROF, APELLIDO_PROF, EMAIL_PROF, CI_PROF, NODO)
SELECT ID_PROF, ID_CATEGORIA, NOMBRE_PROF, APELLIDO_PROF, EMAIL_PROF, CI_PROF, 1
FROM temp_GIRON.dbo.PROFESOR_DATOS_GIRON

INSERT INTO PROFESOR_MATERIA_GIRON(ID_PROF, ID_MATERIA, NODO)
SELECT ID_PROF, ID_MATERIA, 1
FROM [BASE_UPS].UPS.[public].profesor_materia
WHERE ID_MATERIA IN (SELECT ID_MATERIA from MATERIA_GIRON)



/*MATERIA Y ESTUDIANTE*/
--temp
INSERT INTO ESTUDIANTE_MATERIA_GIRON (ID_ESTUDIANTE, ID_MATERIA, NODO)
SELECT ID_ESTUDIANTE, ID_MATERIA, 1
FROM [BASE_UPS].UPS.[public].estudiante_materia
WHERE ID_MATERIA IN (SELECT ID_MATERIA from MATERIA_GIRON)

INSERT INTO ESTUDIANTE_GIRON (ID_ESTUDIANTE, ID_CARRERA, NOMBRE_EST, APELLIDO_EST, EMAIL_EST, CI_EST, FECHA_INICIO, FECHA_SALIDA, NODO)
SELECT ID_ESTUDIANTE, ID_CARRERA, NOMBRE_EST, APELLIDO_EST, EMAIL_EST, CI_EST, FECHA_INICIO, FECHA_SALIDA, 1
FROM [BASE_UPS].UPS.[public].estudiante
WHERE ID_CARRERA IN (SELECT ID_CARRERA from CARRERA_GIRON)

--vale
INSERT INTO ESTUDIANTE_GIRON (ID_ESTUDIANTE, ID_CARRERA, NOMBRE_EST, APELLIDO_EST, EMAIL_EST, CI_EST, FECHA_INICIO, FECHA_SALIDA, NODO)
SELECT ID_ESTUDIANTE, ID_CARRERA, NOMBRE_EST, APELLIDO_EST, EMAIL_EST, CI_EST, FECHA_INICIO, FECHA_SALIDA, 1
FROM temp_GIRON.dbo.ESTUDIANTE_GIRON

INSERT INTO ESTUDIANTE_MATERIA_GIRON (ID_ESTUDIANTE, ID_MATERIA, NODO)
SELECT ID_ESTUDIANTE, ID_MATERIA, 1
FROM [BASE_UPS].UPS.[public].estudiante_materia
WHERE ID_MATERIA IN (SELECT ID_MATERIA from MATERIA_GIRON)



INSERT INTO PROFESOR_NOMINA (ID_PRO, SALARIO, FECHA_INICIO, FECHA_SALIDA)
SELECT ID_PROF, SALARIO, FECHA_INICIO, FECHA_SALIDA
FROM [BASE_UPS].UPS.[public].profesor